### ISSUE TITLE
Project skeleton

### ISSUE THREAD

**Issue by matthewdking** [facn2/Path18#10]
Set up the boiler plate for the project with these technical tasks:
- [x] set up express and handlebars server #12 
- [x] initialise on heroku #13 
- [x] travis and testing environment #15 
- [x] database #16
- [x] linter and pre-commit #14 
- [x] file structure #11

**Comment by Heathercoraje** [comment]
done!
