### ISSUE TITLE
User Journey 

### ISSUE THREAD

**Issue by veredrec** [facn2/Path18#3]
## As a user I can browse a variety of career paths and view detailed information about the ones that I am interested in.

**User Stories:**
As a user I can: 
- [ ] read welcome page and instructions on how to use the app #4 
- [ ] view card with job and decide if I like / dislike it #7
- [ ] click on card to view more details #5
- [ ] View list of jobs I like #6
- [ ] click on job to view details on the job and career path #8
- [ ] read details instructions for the app in the help page #9
