### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by matthewdking** [facn2/Path18#4]
#3 

**As a user I want to...**
> View a welcome page with instructions about the app

- [ ] create view and route for welcome page
- [ ] add text content
- [ ] add 'get started' button and redirect to main page
- [ ] style
- [ ] tests
