### ISSUE TITLE
Create career card

### ISSUE THREAD

**Issue by ghost** [facn2/Path18#7]
#3
 
**As a user I want to...**
 > View card with job and decide if I like / dislike it

- [ ] create view and route for career swiping  #29 
- [ ] query database for careers #30 
- [ ] style card with css #31 
- [ ] implement swipe functionality
- [ ] tests #32
