### ISSUE TITLE
View details on the job career path

### ISSUE THREAD

**Issue by veredrec** [facn2/Path18#8]
#3 
**As a user I want to...**
> click on job to view details on the job and career path
- [ ] create view and route for job-detail page
- [ ] add content to job-detail page
- [ ] query database for job information
- [ ] style
- [ ] tests
